[package]
name = "layer-console"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.32"
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_24"] }
gtk4-layer-shell = "0.8.0"
nix = { version = "0.31.0", features = ["user"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_ignored = "0.1.10"
toml = { version = "1.1.0", features = ["serde", "std"] }
vte4 = { version = "0.10", features = ["v0_78"] }
